# Generated by Django 6.0.1 on 2026-01-17 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='idade',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ex: 3-6 Meses, 4 Anos, 10-12 Anos', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('bebe_menino', 'Bebé Menino 👶💙'), ('bebe_menina', 'Bebé Menina 👶🩷'), ('rapaz', 'Rapaz 👦'), ('rapariga', 'Rapariga 👧')], default='rapaz', max_length=20),
        ),
    ]
