# Generated by Django 6.0.1 on 2026-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_criado_em_produto_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Detalhes do produto', null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='idade',
            field=models.CharField(help_text='Ex: 3-6 Meses, 4 Anos', max_length=50),
        ),
    ]
