# Generated by Django 6.0.1 on 2026-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
